# -*- coding: utf-8 -*-
"""
Created on Sun Jan 08 13:37:39 2017

@author: Stergios
"""

replace_characters = {u'ó' : 'o',
                      u'ã' : 'a',
                      u'ü' : 'u',
                      u'í' : 'i',
                      u'é' : 'e'}

driver_mapping = {'hamilton' : 'Lewis Hamilton',
                'heidfeld' : 'Nick Heidfeld',
                'rosberg' : 'Nico Rosberg',
                'alonso' : 'Fernando Alonso',
                'kovalainen' : 'Heikki Kovalainen',
                'nakajima' : 'Kazuki Nakajima',
                'bourdais' : 'Sebastien Bourdais',
                'raikkonen' : 'Kimi Raikkonen',
                'kubica' : 'Robert Kubica',
                'glock' : 'Timo Glock',
                'sato' : 'Takuma Sato',
                'piquet_jr' : 'Nelson Piquet Jr.',
                'massa' : 'Felipe Massa',
                'coulthard' : 'David Coulthard',
                'trulli' : 'Jarno Trulli',
                'sutil' : 'Adrian Sutil',
                'webber' : 'Mark Webber',
                'button' : 'Jenson Button',
                'davidson' : 'Anthony Davidson',
                'vettel' : 'Sebastian Vettel',
                'fisichella' : 'Giancarlo Fisichella',
                'barrichello' : 'Rubens Barrichello',
                'ralf_schumacher' : 'Ralf Schumacher',
                'liuzzi' : 'Vitantonio Liuzzi',
                'wurz' : 'Alexander Wurz',
                'speed' : 'Scott Speed',
                'albers' : 'Christijan Albers',
                'markus_winkelhock' : 'Markus Winkelhock',
                'yamamoto' : 'Sakon Yamamoto',
                'michael_schumacher' : 'Michael Schumacher',
                'montoya' : 'Juan Pablo Montoya',
                'klien' : 'Christian Klien',
                'monteiro' : 'Tiago Monteiro',
                'ide' : 'Yuji Ide',
                'villeneuve' : 'Jacques Villeneuve',
                'montagny' : 'Franck Montagny',
                'rosa' : 'Pedro de la Rosa',
                'doornbos' : 'Robert Doornbos',
                'karthikeyan' : 'Narain Karthikeyan',
                'friesacher' : 'Patrick Friesacher',
                'zonta' : 'Ricardo Zonta',
                'pizzonia' : 'Antonio Pizzonia',
                'matta' : 'Cristiano da Matta',
                'panis' : 'Olivier Panis',
                'pantano' : 'Giorgio Pantano',
                'bruni' : 'Gianmaria Bruni',
                'baumgartner' : 'Zsolt Baumgartner',
                'gene' : 'Marc Gene',
                'frentzen' : 'Heinz-Harald Frentzen',
                'verstappen' : 'Jos Verstappen',
                'wilson' : 'Justin Wilson',
                'firman' : 'Ralph Firman',
                'kiesa' : 'Nicolas Kiesa',
                'burti' : 'Luciano Burti',
                'alesi' : 'Jean Alesi',
                'irvine' : 'Eddie Irvine',
                'hakkinen' : 'Mika Hakkinen',
                'marques' : 'Tarso Marques',
                'bernoldi' : 'Enrique Bernoldi',
                'mazzacane' : 'Gaston Mazzacane',
                'enge' : 'Tomas Enge',
                'yoong' : 'Alex Yoong',
                'salo' : 'Mika Salo',
                'diniz' : 'Pedro Diniz',
                'herbert' : 'Johnny Herbert',
                'mcnish' : 'Allan McNish',
                'buemi' : 'Sebastien Buemi',
                'takagi' : 'Toranosuke Takagi',
                'badoer' : 'Luca Badoer',
                'zanardi' : 'Alessandro Zanardi',
                'damon_hill' : 'Damon Hill',
                'sarrazin' : 'Stephane Sarrazin',
                'rosset' : 'Ricardo Rosset',
                'tuero' : 'Esteban Tuero',
                'nakano' : 'Shinji Nakano',
                'magnussen' : 'Jan Magnussen',
                'berger' : 'Gerhard Berger',
                'larini' : 'Nicola Larini',
                'katayama' : 'Ukyo Katayama',
                'sospiri' : 'Vincenzo Sospiri',
                'morbidelli' : 'Gianni Morbidelli',
                'fontana' : 'Norberto Fontana',
                'lamy' : 'Pedro Lamy',
                'brundle' : 'Martin Brundle',
                'montermini' : 'Andrea Montermini',
                'lavaggi' : 'Giovanni Lavaggi',
                'blundell' : 'Mark Blundell',
                'suzuki' : 'Aguri Suzuki',
                'inoue' : 'Taki Inoue',
                'moreno' : 'Roberto Moreno',
                'wendlinger' : 'Karl Wendlinger',
                'gachot' : 'Bertrand Gachot',
                'schiattarella' : 'Domenico Schiattarella',
                'martini' : 'Pierluigi Martini',
                'mansell' : 'Nigel Mansell',
                'boullion' : 'Jean-Christophe Boullion',
                'papis' : 'Massimiliano Papis',
                'deletraz' : 'Jean-Denis Deletraz',
                'tarquini' : 'Gabriele Tarquini',
                'comas' : 'erik Comas',
                'brabham' : 'David Brabham',
                'senna' : 'Ayrton Senna',
                'bernard' : 'eric Bernard',
                'fittipaldi' : 'Christian Fittipaldi',
                'alboreto' : 'Michele Alboreto',
                'beretta' : 'Olivier Beretta',
                'ratzenberger' : 'Roland Ratzenberger',
                'belmondo' : 'Paul Belmondo',
                'lehto' : 'Jyrki Jarvilehto',
                'cesaris' : 'Andrea de Cesaris',
                'gounon' : 'Jean-Marc Gounon',
                'alliot' : 'Philippe Alliot',
                'adams' : 'Philippe Adams',
                'dalmas' : 'Yannick Dalmas',
                'noda' : 'Hideki Noda',
                'lagorce' : 'Franck Lagorce',
                'prost' : 'Alain Prost',
                'warwick' : 'Derek Warwick',
                'patrese' : 'Riccardo Patrese',
                'barbazza' : 'Fabrizio Barbazza',
                'andretti' : 'Michael Andretti',
                'capelli' : 'Ivan Capelli',
                'boutsen' : 'Thierry Boutsen',
                'apicella' : 'Marco Apicella',
                'naspetti' : 'Emanuele Naspetti',
                'toshio_suzuki' : 'Toshio Suzuki',
                'gugelmin' : 'Mauricio Gugelmin',
                'poele' : 'Eric van de Poele',
                'grouillard' : 'Olivier Grouillard',
                'chiesa' : 'Andrea Chiesa',
                'modena' : 'Stefano Modena',
                'amati' : 'Giovanna Amati',
                'caffi' : 'Alex Caffi',
                'bertaggia' : 'Enrico Bertaggia',
                'mccarthy' : 'Perry McCarthy',
                'lammers' : 'Jan Lammers',
                'piquet' : 'Nelson Piquet',
                'satoru_nakajima' : 'Satoru Nakajima',
                'pirro' : 'Emanuele Pirro',
                'johansson' : 'Stefan Johansson',
                'bailey' : 'Julian Bailey',
                'chaves' : 'Pedro Chaves',
                'bartels' : 'Michael Bartels',
                'hattori' : 'Naoki Hattori',
                'nannini' : 'Alessandro Nannini',
                'schneider' : 'Bernd Schneider',
                'barilla' : 'Paolo Barilla',
                'foitek' : 'Gregor Foitek',
                'langes' : 'Claudio Langes',
                'gary_brabham' : 'Gary Brabham',
                'donnelly' : 'Martin Donnelly',
                'giacomelli' : 'Bruno Giacomelli',
                'alguersuari' : 'Jaime Alguersuari',
                'grosjean' : 'Romain Grosjean',
                'kobayashi' : 'Kamui Kobayashi',
                'palmer' : 'Jonathan Palmer',
                'danner' : 'Christian Danner',
                'cheever' : 'Eddie Cheever',
                'sala' : 'Luis Perez-Sala',
                'ghinzani' : 'Piercarlo Ghinzani',
                'weidler' : 'Volker Weidler',
                'raphanel' : 'Pierre-Henri Raphanel',
                'arnoux' : 'Rene Arnoux',
                'joachim_winkelhock' : 'Joachim Winkelhock',
                'larrauri' : 'Oscar Larrauri',
                'streiff' : 'Philippe Streiff',
                'campos' : 'Adrian Campos',
                'schlesser' : 'Jean-Louis Schlesser',
                'fabre' : 'Pascal Fabre',
                'fabi' : 'Teo Fabi',
                'forini' : 'Franco Forini',
                'laffite' : 'Jacques Laffite',
                'angelis' : 'Elio de Angelis',
                'dumfries' : 'Johnny Dumfries',
                'tambay' : 'Patrick Tambay',
                'surer' : 'Marc Surer',
                'keke_rosberg' : 'Keke Rosberg',
                'jones' : 'Alan Jones',
                'rothengatter' : 'Huub Rothengatter',
                'berg' : 'Allen Berg',
                'manfred_winkelhock' : 'Manfred Winkelhock',
                'lauda' : 'Niki Lauda',
                'hesnault' : 'Francois Hesnault',
                'baldi' : 'Mauro Baldi',
                'bellof' : 'Stefan Bellof',
                'acheson' : 'Kenny Acheson',
                'watson' : 'John Watson',
                'cecotto' : 'Johnny Cecotto',
                'gartner' : 'Jo Gartner',
                'corrado_fabi' : 'Corrado Fabi',
                'thackwell' : 'Mike Thackwell',
                'serra' : 'Chico Serra',
                'sullivan' : 'Danny Sullivan',
                'salazar' : 'Eliseo Salazar',
                'guerrero' : 'Roberto Guerrero',
                'boesel' : 'Raul Boesel',
                'jarier' : 'Jean-Pierre Jarier',
                'villeneuve_sr' : 'Jacques Villeneuve Sr.',
                'reutemann' : 'Carlos Reutemann',
                'mass' : 'Jochen Mass',
                'borgudd' : 'Slim Borgudd',
                'pironi' : 'Didier Pironi',
                'gilles_villeneuve' : 'Gilles Villeneuve',
                'paletti' : 'Riccardo Paletti',
                'henton' : 'Brian Henton',
                'daly' : 'Derek Daly',
                'mario_andretti' : 'Mario Andretti',
                'villota' : 'Emilio de Villota',
                'lees' : 'Geoff Lees',
                'byrne' : 'Tommy Byrne',
                'keegan' : 'Rupert Keegan',
                'rebaque' : 'Hector Rebaque',
                'gabbiani' : 'Beppe Gabbiani',
                'cogan' : 'Kevin Cogan',
                'guerra' : 'Miguel Angel Guerra',
                'stohr' : 'Siegfried Stohr',
                'zunino' : 'Ricardo Zunino',
                'londono' : 'Ricardo Londono',
                'jabouille' : 'Jean-Pierre Jabouille',
                'francia' : 'Giorgio Francia',
                'depailler' : 'Patrick Depailler',
                'scheckter' : 'Jody Scheckter',
                'regazzoni' : 'Clay Regazzoni',
                'emerson_fittipaldi' : 'Emerson Fittipaldi',
                'kennedy' : 'Dave Kennedy',
                'south' : 'Stephen South',
                'needell' : 'Tiff Needell',
                'desire_wilson' : 'Desire Wilson',
                'ertl' : 'Harald Ertl',
                'brambilla' : 'Vittorio Brambilla',
                'hunt' : 'James Hunt',
                'merzario' : 'Arturo Merzario',
                'stuck' : 'Hans-Joachim Stuck',
                'brancatelli' : 'Gianfranco Brancatelli',
                'ickx' : 'Jacky Ickx',
                'gaillard' : 'Patrick Gaillard',
                'ribeiro' : 'Alex Ribeiro',
                'peterson' : 'Ronnie Peterson',
                'lunger' : 'Brett Lunger',
                'ongais' : 'Danny Ongais',
                'leoni' : 'Lamberto Leoni',
                'galica' : 'Divina Galica',
                'stommelen' : 'Rolf Stommelen',
                'colombo' : 'Alberto Colombo',
                'trimmer' : 'Tony Trimmer',
                'binder' : 'Hans Binder',
                'bleekemolen' : 'Michael Bleekemolen',
                'gimax' : 'Carlo Franchi',
                'rahal' : 'Bobby Rahal',
                'pace' : 'Carlos Pace',
                'ian_scheckter' : 'Ian Scheckter',
                'pryce' : 'Tom Pryce',
                'hoffmann' : 'Ingo Hoffmann',
                'zorzi' : 'Renzo Zorzi',
                'nilsson' : 'Gunnar Nilsson',
                'perkins' : 'Larry Perkins',
                'hayje' : 'Boy Lunger',
                'neve' : 'Patrick Neve',
                'purley' : 'David Purley',
                'andersson' : 'Conny Andersson',
                'dryver' : 'Bernard de Dryver',
                'oliver' : 'Jackie Oliver',
                'kozarowitzky' : 'Mikko Kozarowitzky',
                'sutcliffe' : 'Andy Sutcliffe',
                'edwards' : 'Guy Edwards',
                'mcguire' : 'Brian McGuire',
                'schuppan' : 'Vern Schuppan',
                'heyer' : 'Hans Heyer',
                'pilette' : 'Teddy Pilette',
                'ashley' : 'Ian Ashley',
                'kessel' : 'Loris Kessel',
                'takahashi' : 'Kunimitsu Takahashi',
                'hoshino' : 'Kazuyoshi Hoshino',
                'takahara' : 'Noritake Takahara',
                'lombardi' : 'Lella Lombardi',
                'evans' : 'Bob Evans',
                'leclere' : 'Michel Leclere',
                'amon' : 'Chris Amon',
                'zapico' : 'Emilio Zapico',
                'pescarolo' : 'Henri Pescarolo',
                'nelleman' : 'Jac Nelleman',
                'magee' : 'Damien Magee',
                'wilds' : 'Mike Wilds',
                'pesenti_rossi' : 'Alessandro Pesenti-Rossi',
                'stuppacher' : 'Otto Stuppacher',
                'brown' : 'Warwick Brown',
                'hasemi' : 'Masahiro Hasemi',
                'donohue' : 'Mark Donohue',
                'hill' : 'Graham Hill',
                'wilson_fittipaldi' : 'Wilson Fittipaldi',
                'tunmer' : 'Guy Tunmer',
                'keizan' : 'Eddie Keizan',
                'charlton' : 'Dave Charlton',
                'brise' : 'Tony Brise',
                'wunderink' : 'Roelof Wunderink',
                'migault' : 'Francois Migault',
                'palm' : 'Torsten Palm',
                'lennep' : 'Gijs van Lennep',
                'fushida' : 'Hiroshi Fushida',
                'nicholson' : 'John Nicholson',
                'morgan' : 'Dave Morgan',
                'crawford' : 'Jim Crawford',
                'vonlanthen' : 'Jo Vonlanthen',
                'hulme' : 'Denny Hulme',
                'hailwood' : 'Mike Hailwood',
                'beltoise' : 'Jean-Pierre Beltoise',
                'ganley' : 'Howden Ganley',
                'robarts' : 'Richard Robarts',
                'revson' : 'Peter Revson',
                'driver' : 'Paddy Driver',
                'belso' : 'Tom Belso',
                'redman' : 'Brian Redman',
                'opel' : 'Rikky von Opel',
                'schenken' : 'Tim Schenken',
                'larrousse' : 'Gerard Larrousse',
                'kinnunen' : 'Leo Kinnunen',
                'wisell' : 'Reine Wisell',
                'roos' : 'Bertil Roos',
                'dolhem' : 'Jose Dolhem',
                'gethin' : 'Peter Gethin',
                'bell' : 'Derek Bell',
                'hobbs' : 'David Hobbs',
                'quester' : 'Dieter Quester',
                'koinigg' : 'Helmuth Koinigg',
                'facetti' : 'Carlo Facetti',
                'wietzes' : 'Eppie Wietzes',
                'cevert' : 'Francois Cevert',
                'stewart' : 'Jackie Stewart',
                'beuttler' : 'Mike Beuttler',
                'galli' : 'Nanni Galli',
                'bueno' : 'Luiz Bueno',
                'follmer' : 'George Follmer',
                'adamich' : 'Andrea de Adamich',
                'pretorius' : 'Jackie Pretorius',
                'williamson' : 'Roger Williamson',
                'mcrae' : 'Graham McRae',
                'marko' : 'Helmut Marko',
                'walker' : 'David Walker',
                'roig' : 'Alex Soler-Roig',
                'love' : 'John Love',
                'surtees' : 'John Surtees',
                'barber' : 'Skip Barber',
                'brack' : 'Bill Brack',
                'posey' : 'Sam Posey',
                'rodriguez' : 'Pedro Rodriguez',
                'siffert' : 'Jo Siffert',
                'bonnier' : 'Jo Bonnier',
                'mazet' : 'Francois Mazet',
                'jean' : 'Max Jean',
                'elford' : 'Vic Elford',
                'moser' : 'Silvio Moser',
                'eaton' : 'George Eaton',
                'lovely' : 'Pete Lovely',
                'craft' : 'Chris Craft',
                'Cannoc' : 'John Cannon',
                'jack_brabham' : 'Jack Brabham',
                'miles' : 'John Miles',
                'rindt' : 'Jochen Rindt',
                'gavin' : 'Johnny Servoz-Gavin',
                'mclaren' : 'Bruce McLaren',
                'courage' : 'Piers Courage',
                'klerk' : 'Peter de Klerk',
                'giunti' : 'Ignazio Giunti',
                'gurney' : 'Dan Gurney',
                'hahne' : 'Hubert Hahne',
                'hutchison' : 'Gus Hutchison',
                'westbury' : 'Peter Westbury',
                'tingle' : 'Sam Tingle',
                'rooyen' : 'Basil van Rooyen',
                'attwood' : 'Richard Attwood',
                'pease' : 'Al Pease',
                'cordts' : 'John Cordts',
                'clark' : 'Jim Clark',
                'spence' : 'Mike Spence',
                'scarfiotti' : 'Ludovico Scarfiotti',
                'bianchi' : 'Lucien Bianchi',
                'jo_schlesser' : 'Jo Schlesser',
                'widdows' : 'Robin Widdows',
                'ahrens' : 'Kurt Ahrens',
                'gardner' : 'Frank Gardner',
                'unser' : 'Bobby Unser',
                'solana' : 'Moises Solana',
                'anderson' : 'Bob Anderson',
                'botha' : 'Luki Botha',
                'bandini' : 'Lorenzo Bandini',
                'ginther' : 'Richie Ginther',
                'parkes' : 'Mike Parkes',
                'irwin' : 'Chris Irwin',
                'ligier' : 'Guy Ligier',
                'rees' : 'Alan Rees',
                'hart' : 'Brian Hart',
                'fisher' : 'Mike Fisher',
                'tom_jones' : 'Tom Jones',
                'baghetti' : 'Giancarlo Baghetti',
                'williams' : 'Jonathan Williams',
                'bondurant' : 'Bob Bondurant',
                'arundell' : 'Peter Arundell',
                'vic_wilson' : 'Vic Wilson',
                'taylor' : 'John Taylor',
                'lawrence' : 'Chris Lawrence',
                'trevor_taylor' : 'Trevor Taylor',
                'geki' : 'Giacomo Russo',
                'phil_hill' : 'Phil Hill',
                'ireland' : 'Innes Ireland',
                'bucknum' : 'Ronnie Bucknum',
                'hawkins' : 'Paul Hawkins',
                'prophet' : 'David Prophet',
                'maggs' : 'Tony Maggs',
                'blokdyk' : 'Trevor Blokdyk',
                'lederle' : 'Neville Lederle',
                'serrurier' : 'Doug Serrurier',
                'niemann' : 'Brausch Niemann',
                'pieterse' : 'Ernie Pieterse',
                'puzey' : 'Clive Puzey',
                'reed' : 'Ray Reed',
                'clapham' : 'David Clapham',
                'blignaut' : 'Alex Blignaut',
                'gregory' : 'Masten Gregory',
                'rhodes' : 'John Rhodes',
                'raby' : 'Ian Raby',
                'rollinson' : 'Alan Rollinson',
                'gubby' : 'Brian Gubby',
                'mitter' : 'Gerhard Mitter',
                'bussinello' : 'Roberto Bussinello',
                'vaccarella' : 'Nino Vaccarella',
                'bassi' : 'Giorgio Bassi',
                'trintignant' : 'Maurice Trintignant',
                'collomb' : 'Bernard Collomb',
                'andre_pilette' : 'Andre Pilette',
                'beaufort' : 'Carel Godin de Beaufort',
                'barth' : 'Edgar Barth',
                'cabral' : 'Mario de Araujo Cabral',
                'hansgen' : 'Walt Hansgen',
                'sharp' : 'Hap Sharp',
                'mairesse' : 'Willy Mairesse',
                'campbell-jones' : 'John Campbell-Jones',
                'burgess' : 'Ian Burgess',
                'settember' : 'Tony Settember',
                'estefano' : 'Nasif Estefano',
                'hall' : 'Jim Hall',
                'parnell' : 'Tim Parnell',
                'kuhnke' : 'Kurt Kuhnke',
                'ernesto_brambilla' : 'Ernesto Brambilla',
                'lippi' : 'Roberto Lippi',
                'seiffert' : 'Gunther Seiffert',
                'abate' : 'Carlo Abate',
                'starrabba' : 'Gaetano Starrabba',
                'broeker' : 'Peter Broeker',
                'ward' : 'Rodger Ward',
                'vos' : 'Ernie de Vos',
                'dochnal' : 'Frank Dochnal',
                'monarch' : 'Thomas Monarch',
                'lewis' : 'Jackie Lewis',
                'ricardo_rodriguez' : 'Ricardo Rodriguez',
                'seidel' : 'Wolfgang Seidel',
                'salvadori' : 'Roy Salvadori',
                'pon' : 'Ben Pon',
                'slotemaker' : 'Rob Slotemaker',
                'marsh' : 'Tony Marsh',
                'ashmore' : 'Gerry Ashmore',
                'schiller' : 'Heinz Schiller',
                'davis' : 'Colin Davis',
                'chamberlain' : 'Jay Chamberlain',
                'shelly' : 'Tony Shelly',
                'greene' : 'Keith Greene',
                'walter' : 'Heini Walter',
                'prinoth' : 'Ernesto Prinoth',
                'penske' : 'Roger Penske',
                'schroeder' : 'Rob Schroeder',
                'mayer' : 'Timmy Mayer',
                'johnstone' : 'Bruce Johnstone',
                'harris' : 'Mike Harris',
                'hocking' : 'Gary Hocking',
                'vyver' : 'Syd van der Vyver',
                'moss' : 'Stirling Moss',
                'trips' : 'Wolfgang von Trips',
                'allison' : 'Cliff Allison',
                'herrmann' : 'Hans Herrmann',
                'brooks' : 'Tony Brooks',
                'may' : 'Michael May',
                'henry_taylor' : 'Henry Taylor',
                'gendebien' : 'Olivier Gendebien',
                'scarlatti' : 'Giorgio Scarlatti',
                'naylor' : 'Brian Naylor',
                'bordeu' : 'Juan Manuel Bordeu',
                'fairman' : 'Jack Fairman',
                'natili' : 'Massimo Natili',
                'monteverdi' : 'Peter Monteverdi',
                'pirocchi' : 'Renato Pirocchi',
                'duke' : 'Geoff Duke',
                'thiele' : 'Alfonso Thiele',
                'boffa' : 'Menato Boffa',
                'ryan' : 'Peter Ryan',
                'ruby' : 'Lloyd Ruby',
                'ken_miles' : 'Ken Miles',
                'menditeguy' : 'Carlos Menditeguy',
                'larreta' : 'Alberto Rodriguez Larreta',
                'gonzalez' : 'Jose Froilan Gonzalez',
                'bonomi' : 'Roberto Bonomi',
                'munaron' : 'Gino Munaron',
                'schell' : 'Harry Schell',
                'stacey' : 'Alan Stacey',
                'chimeri' : 'Ettore Chimeri',
                'creus' : 'Antonio Creus',
                'bristow' : 'Chris Bristow',
                'halford' : 'Bruce Halford',
                'daigh' : 'Chuck Daigh',
                'reventlow' : 'Lance Reventlow',
                'rathmann' : 'Jim Rathmann',
                'goldsmith' : 'Paul Goldsmith',
                'branson' : 'Don Branson',
                'thomson' : 'Johnny Thomson',
                'johnson' : 'Eddie Johnson',
                'veith' : 'Bob Veith',
                'tingelstad' : 'Bud Tingelstad',
                'christie' : 'Bob Christie',
                'amick' : 'Red Amick',
                'darter' : 'Duane Carter',
                'homeier' : 'Bill Homeier',
                'hartley' : 'Gene Hartley',
                'stevenson' : 'Chuck Stevenson',
                'grim' : 'Bobby Grim',
                'templeman' : 'Shorty Templeman',
                'hurtubise' : 'Jim Hurtubise',
                'bryan' : 'Jimmy Bryan',
                'ruttman' : 'Troy Ruttman',
                'sachs' : 'Eddie Sachs',
                'freeland' : 'Don Freeland',
                'bettenhausen' : 'Tony Bettenhausen',
                'weiler' : 'Wayne Weiler',
                'foyt' : 'Anthony Foyt',
                'russo' : 'Eddie Russo',
                'boyd' : 'Johnny Boyd',
                'force' : 'Gene Force',
                'mcwithey' : 'Jim McWithey',
                'sutton' : 'Len Sutton',
                'dick_rathmann' : 'Dick Rathmann',
                'herman' : 'Al Herman',
                'dempsey_wilson' : 'Dempsey Wilson',
                'mike_taylor' : 'Mike Taylor',
                'flockhart' : 'Ron Flockhart',
                'piper' : 'David Piper',
                'cabianca' : 'Giulio Cabianca',
                'drogo' : 'Piero Drogo',
                'gamble' : 'Fred Gamble',
                'owen' : 'Arthur Owen',
                'gould' : 'Horace Gould',
                'drake' : 'Bob Drake',
                'bueb' : 'Ivor Bueb',
                'Changy' : 'Alain de Changy',
                'filippis' : 'Maria de Filippis',
                'lucienbonnet' : 'Jean Lucienbonnet',
                'testut' : 'Andre Testut',
                'behra' : 'Jean Behra',
                'paul_russo' : 'Paul Russo',
                'daywalt' : 'Jimmy Daywalt',
                'arnold' : 'Chuck Arnold',
                'keller' : 'Al Keller',
                'flaherty' : 'Pat Flaherty',
                'cheesbourg' : 'Bill Cheesbourg',
                'ray_crawford' : 'Ray Crawford',
                'turner' : 'Jack Turner',
                'weyant' : 'Chuck Weyant',
                'larson' : 'Jud Larson',
                'magill' : 'Mike Magill',
                'shelby' : 'Carroll Shelby',
                'orey' : 'Fritz d\'Orey',
                'fontes' : 'Azdrubal Fontes',
                'ashdown' : 'Peter Ashdown',
                'bill_moss' : 'Bill Moss',
                'dennis_taylor' : 'Dennis Taylor',
                'blanchard' : 'Harry Blanchard',
                'tomaso' : 'Alessandro de Tomaso',
                'constantine' : 'George Constantine',
                'said' : 'Bob Said',
                'cade' : 'Phil Cade',
                'musso' : 'Luigi Musso',
                'hawthorn' : 'Mike Hawthorn',
                'fangio' : 'Juan Fangio',
                'godia' : 'Paco Godia',
                'collins' : 'Peter Collins',
                'kavanagh' : 'Ken Kavanagh',
                'gerini' : 'Gerino Gerini',
                'kessler' : 'Bruce Kessler',
                'emery' : 'Paul Emery',
                'piotti' : 'Luigi Piotti',
                'ecclestone' : 'Bernie Ecclestone',
                'taramazzo' : 'Luigi Taramazzo',
                'chiron' : 'Louis Chiron',
                'lewis-evans' : 'Stuart Lewis-Evans',
                'george_amick' : 'George Amick',
                'reece' : 'Jimmy Reece',
                'parsons' : 'Johnnie Parsons',
                'tolan' : 'Johnnie Tolan',
                'garrett' : 'Billy Garrett',
                'elisian' : 'Ed Elisian',
                'connor' : 'Pat O\'Connor',
                'jerry_unser' : 'Jerry Unser',
                'bisch' : 'Art Bisch',
                'goethals' : 'Christian Goethals',
                'gibson' : 'Dick Gibson',
                'la_caze' : 'Robert La Caze',
                'guelfi' : 'Andre Guelfi',
                'picard' : 'Francois Picard',
                'bridger' : 'Tom Bridger',
                'portago' : 'Alfonso de Portago',
                'perdisa' : 'Cesare Perdisa',
                'castellotti' : 'Eugenio Castellotti',
                'simon' : 'Andre Simon',
                'leston' : 'Les Leston',
                'hanks' : 'Sam Hanks',
                'linden' : 'Andy Linden',
                'teague' : 'Marshall Teague',
                'edmunds' : 'Don Edmunds',
                'agabashian' : 'Fred Agabashian',
                'george' : 'Elmer George',
                'macdowel' : 'Mike MacDowel',
                'mackay-fraser' : 'Herbert MacKay-Fraser',
                'gerard' : 'Bob Gerard',
                'maglioli' : 'Umberto Maglioli',
                'england' : 'Paul England',
                'landi' : 'Chico Landi',
                'uria' : 'Alberto Uria',
                'ramos' : 'Hernando da Silva Ramos',
                'bayol' : 'Elie Bayol',
                'manzon' : 'Robert Manzon',
                'rosier' : 'Louis Rosier',
                'sweikert' : 'Bob Sweikert',
                'griffith' : 'Cliff Griffith',
                'dinsmore' : 'Duke Dinsmore',
                'andrews' : 'Keith Andrews',
                'frere' : 'Paul Frere',
                'villoresi' : 'Luigi Villoresi',
                'scotti' : 'Piero Scotti',
                'chapman' : 'Colin Chapman',
                'titterington' : 'Desmond Titterington',
                'scott_Brown' : 'Archie Scott Brown',
                'volonterio' : 'Ottorino Volonterio',
                'milhoux' : 'Andre Milhoux',
                'graffenried' : 'Toulo de Graffenried',
                'taruffi' : 'Piero Taruffi',
                'farina' : 'Nino Farina',
                'mieres' : 'Roberto Mieres',
                'mantovani' : 'Sergio Mantovani',
                'bucci' : 'Clemar Bucci',
                'iglesias' : 'Jesus Iglesias',
                'ascari' : 'Alberto Ascari',
                'kling' : 'Karl Kling',
                'birger' : 'Pablo Birger',
                'pollet' : 'Jacques Pollet',
                'macklin' : 'Lance Macklin',
                'whiteaway' : 'Ted Whiteaway',
                'davies' : 'Jimmy Davies',
                'faulkner' : 'Walt Faulkner',
                'niday' : 'Cal Niday',
                'cross' : 'Art Cross',
                'vukovich' : 'Bill Vukovich',
                'mcgrath' : 'Jack McGrath',
                'hoyt' : 'Jerry Hoyt',
                'claes' : 'Johnny Claes',
                'peter_walker' : 'Peter Walker',
                'sparken' : 'Mike Sparken',
                'wharton' : 'Ken Wharton',
                'mcalpine' : 'Kenneth McAlpine',
                'marr' : 'Leslie Marr',
                'rolt' : 'Tony Rolt',
                'fitch' : 'John Fitch',
                'lucas' : 'Jean Lucas',
                'bira' : 'Prince Bira',
                'marimon' : 'Onofre Marimon',
                'loyer' : 'Roger Loyer',
                'daponte' : 'Jorge Daponte',
                'nazaruk' : 'Mike Nazaruk',
                'crockett' : 'Larry Crockett',
                'ayulo' : 'Manny Ayulo',
                'armi' : 'Frank Armi',
                'webb' : 'Travis Webb',
                'duncan' : 'Len Duncan',
                'mccoy' : 'Ernie McCoy',
                'swaters' : 'Jacques Swaters',
                'georges_berger' : 'Georges Berger',
                'beauman' : 'Don Beauman',
                'thorne' : 'Leslie Thorne',
                'whitehouse' : 'Bill Whitehouse',
                'riseley_prichard' : 'John Riseley-Prichard',
                'reg_parnell' : 'Reg Parnell',
                'whitehead' : 'Peter Whitehead',
                'brandon' : 'Eric Brandon',
                'alan_brown' : 'Alan Brown',
                'nuckey' : 'Rodney Nuckey',
                'lang' : 'Hermann Lang',
                'helfrich' : 'Theo Helfrich',
                'wacker' : 'Fred Wacker',
                'riu' : 'Giovanni de Riu',
                'galvez' : 'Oscar Galvez',
                'john_barber' : 'John Barber',
                'bonetto' : 'Felice Bonetto',
                'cruz' : 'Adolfo Cruz',
                'nalon' : 'Duke Nalon',
                'scarborough' : 'Carl Scarborough',
                'holland' : 'Bill Holland',
                'bob_scott' : 'Bob Scott',
                'legat' : 'Arthur Legat',
                'cabantous' : 'Yves Cabantous',
                'crook' : 'Tony Crook',
                'jimmy_stewart' : 'Jimmy Stewart',
                'ian_stewart' : 'Ian Stewart',
                'duncan_hamilton' : 'Duncan Hamilton',
                'klodwig' : 'Ernst Klodwig',
                'krause' : 'Rudolf Krause',
                'karch' : 'Oswald Karch',
                'heeks' : 'Willi Heeks',
                'fitzau' : 'Theo Fitzau',
                'adolff' : 'Kurt Adolff',
                'bechem' : 'Gunther Bechem',
                'bauer' : 'Erwin Bauer',
                'hans_stuck' : 'Hans von Stuck',
                'loof' : 'Ernst Loof',
                'scherrer' : 'Albert Scherrer',
                'terra' : 'Max de Terra',
                'hirt' : 'Peter Hirt',
                'carini' : 'Piero Carini',
                'fischer' : 'Rudi Fischer',
                'ulmen' : 'Toni Ulmen',
                'abecassis' : 'George Abecassis',
                'george_connor' : 'George Connor',
                'rigsby' : 'Jim Rigsby',
                'james' : 'Joe James',
                'schindler' : 'Bill Schindler',
                'fonder' : 'George Fonder',
                'banks' : 'Henry Banks',
                'mcdowell' : 'Johnny McDowell',
                'miller' : 'Chet Miller',
                'ball' : 'Bobby Ball',
                'tornaco' : 'Charles de Tornaco',
                'laurent' : 'Roger Laurent',
                'obrien' : 'Robert O\'Brien',
                'gaze' : 'Tony Gaze',
                'charrington' : 'Robin Montgomerie-Charrington',
                'comotti' : 'Franco Comotti',
                'etancelin' : 'Philippe etancelin',
                'poore' : 'Dennis Poore',
                'thompson' : 'Eric Thompson',
                'downing' : 'Ken Downing',
                'graham_whitehead' : 'Graham Whitehead',
                'bianco' : 'Gino Bianco',
                'murray' : 'David Murray',
                'cantoni' : 'Eitel Cantoni',
                'aston' : 'Bill Aston',
                'brudes' : 'Adolf Brudes',
                'riess' : 'Fritz Riess',
                'niedermayr' : 'Helmut Niedermayr',
                'klenk' : 'Hans Klenk',
                'balsa' : 'Marcel Balsa',
                'schoeller' : 'Rudolf Schoeller',
                'pietsch' : 'Paul Pietsch',
                'peters' : 'Josef Peters',
                'lof' : 'Dries van der Lof',
                'flinterman' : 'Jan Flinterman',
                'dusio' : 'Piero Dusio',
                'crespo' : 'Alberto Crespo',
                'rol' : 'Franco Rol',
                'sanesi' : 'Consalvo Sanesi',
                'guy_mairesse' : 'Guy Mairesse',
                'louveau' : 'Henri Louveau',
                'wallard' : 'Lee Wallard',
                'forberg' : 'Carl Forberg',
                'rose' : 'Mauri Rose',
                'mackey' : 'Bill Mackey',
                'green' : 'Cecil Green',
                'walt_brown' : 'Walt Brown',
                'hellings' : 'Mack Hellings',
                'levegh' : 'Pierre Levegh',
                'chaboud' : 'Eugene Chaboud',
                'gordini' : 'Aldo Gordini',
                'kelly' : 'Joe Kelly',
                'parker' : 'Philip Fotheringham-Parker',
                'shawe_taylor' : 'Brian Shawe Taylor',
                'john_james' : 'John James',
                'branca' : 'Toni Branca',
                'richardson' : 'Ken Richardson',
                'jover' : 'Juan Jover',
                'grignard' : 'Georges Grignard',
                'hampshire' : 'David Hampshire',
                'crossley' : 'Geoff Crossley',
                'fagioli' : 'Luigi Fagioli',
                'harrison' : 'Cuth Harrison',
                'fry' : 'Joe Fry',
                'martin' : 'Eugene Martin',
                'leslie_johnson' : 'Leslie Johnson',
                'biondetti' : 'Clemente Biondetti',
                'pian' : 'Alfredo Pian',
                'sommer' : 'Raymond Sommer',
                'chitwood' : 'Joie Chitwood',
                'fohr' : 'Myron Fohr',
                'ader' : 'Walt Ader',
                'holmes' : 'Jackie Holmes',
                'levrett' : 'Bayliss Levrett',
                'jackson' : 'Jimmy Jackson',
                'pagani' : 'Nello Pagani',
                'pozzi' : 'Charles Pozzi',
                'serafini' : 'Dorino Serafini',
                'cantrell' : 'Bill Cantrell',
                'mantz' : 'Johnny Mantz',
                'kladis' : 'Danny Kladis',
                'oscar_gonzalez' : 'Oscar Gonzalez',
                'hulkenberg' : 'Nico Hulkenberg',
                'petrov' : 'Vitaly Petrov',
                'lopez' : 'Jose Maria Lopez',
                'grassi' : 'Lucas di Grassi',
                'bruno_senna' : 'Bruno Senna',
                'chandhok' : 'Karun Chandhok',
                'maldonado' : 'Pastor Maldonado',
                'resta' : 'Paul di Resta',
                'perez' : 'Sergio Perez',
                'ambrosio' : 'Jerome d\'Ambrosio',
                'ricciardo' : 'Daniel Ricciardo',
                'vergne' : 'Jean-eric Vergne',
                'pic' : 'Charles Pic',
                'chilton' : 'Max Chilton',
                'gutierrez' : 'Esteban Gutierrez',
                'bottas' : 'Valtteri Bottas',
                'garde' : 'Giedo van der Garde',
                'jules_bianchi' : 'Jules Bianchi',
                'kevin_magnussen' : 'Kevin Magnussen',
                'kvyat' : 'Daniil Kvyat',
                'lotterer' : 'Andre Lotterer',
                'ericsson' : 'Marcus Ericsson',
                'stevens' : 'Will Stevens',
                'max_verstappen' : 'Max Verstappen',
                'nasr' : 'Felipe Nasr',
                'sainz' : 'Carlos Sainz',
                'merhi' : 'Roberto Merhi',
                'rossi' : 'Alexander Rossi',
                'jolyon_palmer' : 'Jolyon Palmer',
                'wehrlein' : 'Pascal Wehrlein',
                'haryanto' : 'Rio Haryanto',
                'vandoorne' : 'Stoffel Vandoorne',
                'ocon' : 'Esteban Ocon',
                'leclerc' : 'Charles Leclerc'
                }

constuctor_mapping = {'mclaren' : 'McLaren',
                'bmw_sauber' : 'BMW Sauber',
                'williams' : 'Williams',
                'renault' : 'Renault',
                'toro_rosso' : 'Toro Rosso',
                'ferrari' : 'Ferrari',
                'toyota' : 'Toyota',
                'super_aguri' : 'Super Aguri',
                'red_bull' : 'Red Bull',
                'force_india' : 'Force India',
                'honda' : 'Honda',
                'spyker' : 'Spyker',
                'mf1' : 'MF1',
                'spyker_mf1' : 'Spyker MF1',
                'sauber' : 'Sauber',
                'bar' : 'BAR',
                'jordan' : 'Jordan',
                'minardi' : 'Minardi',
                'jaguar' : 'Jaguar',
                'prost' : 'Prost',
                'arrows' : 'Arrows',
                'benetton' : 'Benetton',
                'brawn' : 'Brawn',
                'stewart' : 'Stewart',
                'tyrrell' : 'Tyrrell',
                'lola' : 'Lola',
                'ligier' : 'Ligier',
                'forti' : 'Forti',
                'footwork' : 'Footwork',
                'pacific' : 'Pacific',
                'simtek' : 'Simtek',
                'team_lotus' : 'Team Lotus',
                'larrousse' : 'Larrousse',
                'brabham' : 'Brabham',
                'dallara' : 'Dallara',
                'fondmetal' : 'Fondmetal',
                'march' : 'March',
                'moda' : 'Andrea Moda',
                'ags' : 'AGS',
                'lambo' : 'Lambo',
                'leyton' : 'Leyton House',
                'coloni' : 'Coloni',
                'eurobrun' : 'Euro Brun',
                'osella' : 'Osella',
                'onyx' : 'Onyx',
                'life' : 'Life',
                'rial' : 'Rial',
                'zakspeed' : 'Zakspeed',
                'ram' : 'RAM',
                'alfa' : 'Alfa Romeo',
                'spirit' : 'Spirit',
                'toleman' : 'Toleman',
                'ats' : 'ATS',
                'theodore' : 'Theodore',
                'fittipaldi' : 'Fittipaldi',
                'ensign' : 'Ensign',
                'shadow' : 'Shadow',
                'wolf' : 'Wolf',
                'merzario' : 'Merzario',
                'kauhsen' : 'Kauhsen',
                'rebaque' : 'Rebaque',
                'surtees' : 'Surtees',
                'hesketh' : 'Hesketh',
                'martini' : 'Martini',
                'brm' : 'BRM',
                'penske' : 'Penske',
                'lec' : 'LEC',
                'mcguire' : 'McGuire',
                'boro' : 'Boro',
                'apollon' : 'Apollon',
                'kojima' : 'Kojima',
                'parnelli' : 'Parnelli',
                'maki' : 'Maki',
                'hill' : 'Embassy Hill',
                'lyncar' : 'Lyncar',
                'trojan' : 'Trojan',
                'amon' : 'Amon',
                'token' : 'Token',
                'iso_marlboro' : 'Iso Marlboro',
                'tecno' : 'Tecno',
                'matra' : 'Matra',
                'politoys' : 'Politoys',
                'connew' : 'Connew',
                'bellasi' : 'Bellasi',
                'tomaso' : 'De Tomaso',
                'cooper' : 'Cooper',
                'eagle' : 'Eagle',
                'lds' : 'LDS',
                'protos' : 'Protos',
                'shannon' : 'Shannon',
                'scirocco' : 'Scirocco',
                're' : 'RE',
                'brp' : 'BRP',
                'porsche' : 'Porsche',
                'derrington' : 'Derrington',
                'gilby' : 'Gilby',
                'stebro' : 'Stebro',
                'emeryson' : 'Emeryson',
                'enb' : 'ENB',
                'jbw' : 'JBW',
                'ferguson' : 'Ferguson',
                'mbm' : 'MBM',
                'behra-porsche' : 'Behra-Porsche',
                'maserati' : 'Maserati',
                'scarab' : 'Scarab',
                'watson' : 'Watson',
                'epperly' : 'Epperly',
                'phillips' : 'Phillips',
                'lesovsky' : 'Lesovsky',
                'trevis' : 'Trevis',
                'meskowski' : 'Meskowski',
                'kurtis_kraft' : 'Kurtis Kraft',
                'kuzma' : 'Kuzma',
                'vhristensen' : 'Christensen',
                'ewing' : 'Ewing',
                'aston_martin' : 'Aston Martin',
                'vanwall' : 'Vanwall',
                'moore' : 'Moore',
                'dunn' : 'Dunn',
                'elder' : 'Elder',
                'sutton' : 'Sutton',
                'fry' : 'Fry',
                'tec-mec' : 'Tec-Mec',
                'connaught' : 'Connaught',
                'alta' : 'Alta',
                'osca' : 'OSCA',
                'gordini' : 'Gordini',
                'stevens' : 'Stevens',
                'bugatti' : 'Bugatti',
                'mercedes' : 'Mercedes',
                'lancia' : 'Lancia',
                'hwm' : 'HWM',
                'schroeder' : 'Schroeder',
                'pawl' : 'Pawl',
                'pankratz' : 'Pankratz',
                'arzani-volpini' : 'Arzani-Volpini',
                'nichels' : 'Nichels',
                'bromme' : 'Bromme',
                'klenk' : 'Klenk',
                'simca' : 'Simca',
                'turner' : 'Turner',
                'del_roy' : 'Del Roy',
                'veritas' : 'Veritas',
                'bmw' : 'BMW',
                'emw' : 'EMW',
                'afm' : 'AFM',
                'frazer_nash' : 'Frazer Nash',
                'sherman' : 'Sherman',
                'deidt' : 'Deidt',
                'era' : 'ERA',
                'butterworth' : 'Aston Butterworth',
                'cisitalia' : 'Cisitalia',
                'lago' : 'Talbot-Lago',
                'hall' : 'Hall',
                'marchese' : 'Marchese',
                'langley' : 'Langley',
                'rae' : 'Rae',
                'olson' : 'Olson',
                'wetteroth' : 'Wetteroth',
                'adams' : 'Adams',
                'snowberger' : 'Snowberger',
                'milano' : 'Milano',
                'hrt' : 'HRT',
                'virgin' : 'Virgin',
                'cooper-maserati' : 'Cooper-Maserati',
                'cooper-osca' : 'Cooper-OSCA',
                'cooper-borgward' : 'Cooper-Borgward',
                'cooper-climax' : 'Cooper-Climax',
                'cooper-castellotti' : 'Cooper-Castellotti',
                'lotus-climax' : 'Lotus-Climax',
                'lotus-maserati' : 'Lotus-Maserati',
                'de_tomaso-osca' : 'De Tomaso-Osca',
                'de_tomaso-alfa_romeo' : 'De Tomaso-Alfa Romeo',
                'lotus-brm' : 'Lotus-BRM',
                'lotus-borgward' : 'Lotus-Borgward',
                'cooper-alfa_romeo' : 'Cooper-Alfa Romeo',
                'de_tomaso-ferrari' : 'De Tomaso-Ferrari',
                'lotus-ford' : 'Lotus-Ford',
                'brabham-brm' : 'Brabham-BRM',
                'brabham-ford' : 'Brabham-Ford',
                'brabham-climax' : 'Brabham-Climax',
                'lds-climax' : 'LDS-Climax',
                'lds-alfa_romeo' : 'LDS-Alfa Romeo',
                'cooper-ford' : 'Cooper-Ford',
                'mclaren-ford' : 'McLaren-Ford',
                'mclaren-seren' : 'McLaren-Serenissima',
                'eagle-climax' : 'Eagle-Climax',
                'eagle-weslake' : 'Eagle-Weslake',
                'brabham-repco' : 'Brabham-Repco',
                'cooper-ferrari' : 'Cooper-Ferrari',
                'cooper-ats' : 'Cooper-ATS',
                'mclaren-brm' : 'McLaren-BRM',
                'cooper-brm' : 'Cooper-BRM',
                'matra-ford' : 'Matra-Ford',
                'brm-ford' : 'BRM-Ford',
                'mclaren-alfa_romeo' : 'McLaren-Alfa Romeo',
                'march-alfa_romeo' : 'March-Alfa Romeo',
                'march-ford' : 'March-Ford',
                'lotus-pw' : 'Lotus-Pratt &amp; Whitney',
                'shadow-ford' : 'Shadow-Ford',
                'shadow-matra' : 'Shadow-Matra',
                'brabham-alfa_romeo' : 'Brabham-Alfa Romeo',
                'lotus_racing' : 'Lotus',
                'marussia' : 'Marussia',
                'caterham' : 'Caterham',
                'lotus_f1' : 'Lotus F1',
                'manor' : 'Manor Marussia',
                'haas' : 'Haas F1 Team',
                }

finishing_statuses = {'disqualified' : 'disqualification',
                    'accident' : 'an accident',
                    'collision' : 'a collision',
                    'engine' : 'an engine problem',
                    'gearbox' : 'a gearbox problem',
                    'transmission' : 'a transmission issue',
                    'clutch' : 'a clutch issue',
                    'hydraulics' : 'a hydraulics problem',
                    'electrical' : 'an electrical problem',
                    'spun off' : 'spuning off',
                    'radiator' : 'a radiator issue',
                    'suspension' : 'a suspension problem',
                    'brakes' : 'a brakes problem',
                    'differential' : 'a differential issue',
                    'overheating' : 'an overheating issue',
                    'mechanical' : 'a mechanical problem',
                    'tyre' : 'a tyre issue',
                    'driver seat' : 'a driver seat issue',
                    'puncture' : 'a puncture',
                    'driveshaft' : 'a driveshaft problem',
                    'retired' : 'unknown reasons',
                    'fuel pressure' : 'a fuel pressure problem',
                    'front wing' : 'a front wing issue',
                    'water pressure' : 'a water pressure problem',
                    'refuelling' : 'a refuelling problem',
                    'wheel' : 'a wheel glitch',
                    'throttle' : 'a throttle problem',
                    'steering' : 'a steering issue',
                    'technical' : 'a technical problem',
                    'electronics' : 'an electronics problem',
                    'broken wing' : 'a broken wing',
                    'heat shield fire' : 'a heat shield fire problem',
                    'exhaust' : 'an exhaust issue',
                    'oil leak' : 'an oil leak',
                    'wheel rim' : 'a wheel rim problem',
                    'water leak' : 'a water leak',
                    'fuel pump' : 'a fuel pump issue',
                    'track rod' : 'a track rod issue',
                    'oil pressure' : 'an oil pressure problem',
                    'withdrew' : 'withdrawal',
                    'engine fire' : 'an engine fire',
                    'tyre puncture' : 'a tyre puncture',
                    'out of fuel' : 'remaining out of fuel',
                    'wheel nut' : 'a wheel nut problem',
                    'not classified' : 'not being classified',
                    'pneumatics' : 'a pneumatics problem',
                    'handling' : 'a handling problem',
                    'rear wing' : 'a rear wing issue',
                    'fire' : 'a fire',
                    'wheel bearing' : 'a wheel bearing problem',
                    'physical' : 'a physical problem',
                    'fuel system' : 'a fuel system issue',
                    'oil line' : 'an oil line issue',
                    'fuel rig' : 'a fuel rig issue',
                    'launch control' : 'a launch control issue',
                    'injured' : 'an injury',
                    'fuel' : 'a fuel problem',
                    'power loss' : 'a power loss problem',
                    'vibrations' : 'increased vibrations',
                    '107% rule' : 'the 107% rule',
                    'safety' : 'a safety problem',
                    'drivetrain' : 'a drivetrain problem',
                    'ignition' : 'an ignition issue',
                    'did not qualify' : 'not qualifying',
                    'injury' : 'an injury',
                    'chassis' : 'a chassis issue',
                    'battery' : 'a battery issue',
                    'stalled' : 'a stalled engine',
                    'halfshaft' : 'a halfshaft issue',
                    'crankshaft' : 'a crankshaft problem',
                    'safety concerns' : 'safety concerns',
                    'not restarted' : 'not restarting',
                    'alternator' : 'an alternator problem',
                    'underweight' : 'being underweight',
                    'safety belt' : 'a safety belt issue',
                    'oil pump' : 'an oil pump issue',
                    'fuel leak' : 'a fuel leak problem',
                    'excluded' : 'being excluded',
                    'did not prequalify' : 'not prequalifying',
                    'injection' : 'an injection issue',
                    'distributor' : 'a distributor issue',
                    'driver unwell' : 'being unwell',
                    'turbo' : 'a turbo problem',
                    'cv joint' : 'a cv joint problem',
                    'water pump' : 'a water pump problem',
                    'fatal accident' : 'a fatal accident',
                    'spark plugs' : 'a spark plugs issue',
                    'fuel pipe' : 'a fuel pipe problem',
                    'eye injury' : 'an eye injury',
                    'oil pipe' : 'an oil pipe problem',
                    'axle' : 'an axle issue',
                    'water pipe' : 'a water pipe issue',
                    'magneto' : 'a magneto issue',
                    'supercharger' : 'a supercharger problem',
                    'engine misfire' : 'engine misfiring',
                    'collision damage' : 'collision damage',
                    'power unit' : 'a power unit issue',
                    'ers' : 'an ers problem',
                    'brake duct' : 'a brake duct issue',

                    }